<template>
  <v-container class="pt-12 px-0">
    <v-row class="justify-center">
        <v-col cols="3"> 
          <side-bar/>   
        </v-col>

        <v-col cols="4" class="">
              <iframe 
                src="https://hsok0070.github.io/remon-devguide-quickstartlivestreaming/simplewatch.html" 
                frameborder="0" 
                style="height:600px;width:400px"
                id="frame"
                ></iframe>
        </v-col>
        <v-col cols="5">
              <chat-container/>
        </v-col>
    
      </v-row>
    </v-container>


</template> 

<script>
import NavBar from '@/components/userNavigation.vue'
import ChatContainer from '@/components/ChatContainer';
export default {
  components: {
    'side-bar' : NavBar,
    ChatContainer
  }
}
</script>

<style scoped>
.container.fill-height { flex-wrap: wrap; } .container.fill-height > .row { flex: 1 1 100%; }
 body {
  background: url('../../../assets/dog.jpg');
} 

/* #app {
  font-family: Helvetica;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #454d54;
  margin-top: 60px;
} */

/* Loading Ripple Animation */
/* Generated by loading.io */
@keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
@-webkit-keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
.lds-ripple {
  position: relative;
}
.lds-ripple div {
  box-sizing: content-box;
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  -webkit-animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
  animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(1) {
  border-color: #000000;
}
.lds-ripple div:nth-child(2) {
  border-color: rgba(0%,0%,0%,0.675);
  -webkit-animation-delay: -1.3s;
  animation-delay: -1.3s;
}
.lds-ripple {
  width: 36px !important;
  height: 36px !important;
  -webkit-transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
  transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
}

#frame{
  background-color: white;
}
#care-vid, #care-chat{
  display: inline-block;
}
#care-chat{
  margin-left: 3em;
  /* height: ; */
}
</style>